### ISSUE TITLE
Version 0.0.5 doesn't work

### ISSUE THREAD

**Issue by Milozzy** [mirkobrombin/PPAExtender#9]
Hi, I install com.github.mirkobrombin.ppaextender_0.0.5_amd64.deb but the app doesn't start.
If I try to launch it form CLI I received this error message:

~$ com.github.mirkobrombin.ppaextender
Traceback (most recent call last):
  File "/usr/local/bin/com.github.mirkobrombin.ppaextender", line 35, in <module>
    from ppaextender import main
  File "/usr/local/bin/ppaextender/main.py", line 23, in <module>
    gi.require_version('Granite', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Granite not available

Thanks

**Comment by mirkobrombin** [comment]
Try installing libgranite-dev
